apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql 
spec:
  selector:
    matchLabels:
      app: mysql 
  template:
    metadata:
      labels:
        app: mysql 
    spec:
      containers:
      - name: mysql 
        image: mysql:5.6
        env: 
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mysqlpwd
                name: mysql-db-pass
        ports:
        - containerPort: 3306
    ####inside my container template i need to attach the volumes also
        volumeMounts: 
          - name: mysql-pvc 
            mountPath: /var/lib/mysql    
          - name: config-script 
            mountPath: /docker-entrypoint-initdb.d
      volumes:
      ####the mapping between your volume inside the container and pvc is happening with the name
        - name: mysql-pvc 
          persistentVolumeClaim: 
            claimName: task-pvc-mysql
        - name: config-script
          configMap:
            name: mysql-config
