apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: task-pv-pod
  name: task-pv-pod
spec:
  containers:
  - image: nginx
    name: task-pv-pod
    ports:
    - containerPort: 80
    volumeMounts: #add this line
      - mountPath: "/usr/share/nginx/html" ###add this line
        name: task-pv-storage
  volumes: 
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim